# Originally generated by OrbStack; now managed in this repo and built by the
# flake (flake.nix). The /etc/nixos/configuration.nix on the machine is no
# longer used.

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Machine-local files generated by OrbStack (incus.nix sets the
      # hostname). Read live from /etc/nixos, which is impure — rebuilds
      # need --impure (see ./rebuild).
      /etc/nixos/incus.nix
      /etc/nixos/orbstack.nix
    ];

  # Extra certificates (mkcert CA, OrbStack root CA, ...). Read live from
  # the OrbStack guest agent, which keeps this file up to date — nothing
  # machine-local is committed to this repo.
  security.pki.certificateFiles = [ /opt/orbstack-guest/run/extra-certs.crt ];

  users.users.duncanbrown = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" "audio" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/duncanbrown";
    homeMode = "700";
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Europe/London";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # NixOS release this machine was first installed with. Never change it.
  system.stateVersion = "25.11";
}
