# OrbStack platform glue: the LXC base module, OrbStack's machine-local
# files, networking and the CA bundle. Nothing here is specific to what
# the machine is used for; see configuration.nix for that.

{ modulesPath, ... }:

{
  imports = [
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Generated by OrbStack (incus.nix sets the hostname). Read live from
    # /etc/nixos, which is impure — rebuilds need --impure (see ./rebuild).
    /etc/nixos/incus.nix
    /etc/nixos/orbstack.nix
  ];

  # Extra certificates (mkcert CA, OrbStack root CA, ...). The OrbStack
  # guest agent keeps this file up to date.
  security.pki.certificateFiles = [ /opt/orbstack-guest/run/extra-certs.crt ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # LXC containers can't mount debugfs; without this the unit fails at boot.
  systemd.units."sys-kernel-debug.mount".enable = false;

  # NixOS release this machine was first installed with. Never change it.
  system.stateVersion = "25.11";
}
